name: Build and Push to ECR

on:
  workflow_dispatch:  # Manual trigger
  push:
    branches: [ main ]
    paths:
      - 'ecr-build/**'
      - '.github/workflows/build-and-push-ecr.yml'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-central-1
        
    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2
      
    - name: Download Ministral 8B Model
      working-directory: ./ecr-build
      env:
        HUGGINGFACE_HUB_TOKEN: ${{ secrets.HUGGINGFACE_HUB_TOKEN }}
      run: |
        # Install huggingface_hub
        pip install huggingface_hub
        
        # Create models directory
        mkdir -p models/Ministral-8B-Instruct-2410
        
        # Download the model
        python -c "
        from huggingface_hub import snapshot_download
        import os
        
        print('🚀 Downloading Ministral 8B model...')
        print('This may take a while as the model is ~16GB...')
        
        try:
            snapshot_download(
                repo_id='mistralai/Ministral-8B-Instruct-2410',
                local_dir='models/Ministral-8B-Instruct-2410',
                resume_download=True
            )
            print('✅ Model downloaded successfully!')
        except Exception as e:
            print(f'❌ Error downloading model: {e}')
            exit(1)
        "
        
    - name: Build, tag, and push image to Amazon ECR
      working-directory: ./ecr-build
      run: |
        # Build the Docker image
        docker build -t mistral8b-vllm .
        
        # Tag for ECR
        docker tag mistral8b-vllm:latest 396360117331.dkr.ecr.eu-central-1.amazonaws.com/mistral8b-vllm:latest
        
        # Push to ECR
        docker push 396360117331.dkr.ecr.eu-central-1.amazonaws.com/mistral8b-vllm:latest
        
    - name: Verify push
      run: |
        echo "✅ Docker image pushed to ECR successfully!"
        echo "Image: 396360117331.dkr.ecr.eu-central-1.amazonaws.com/mistral8b-vllm:latest"
